Reskin or only
topcoder-platform/tc-online-review pull request #221
Opened 2022-12-16 02:45 UTC by dedywahyudi

2022-12-16 16:43 UTC, jpeg22 approved these changes

2022-12-17 15:29 UTC, eisbilir requested changes

2022-12-17 15:29 UTC, eisbilir commented on src/main/java/com/cronos/onlinereview/actions/projectdetails/BaseProjectDetailsAction.java
> +    protected CorrectnessCheckResult checkForCorrectProjectId(HttpServletRequest request,
There is no need to add project_id parameter to the "Download Final Fix" action. The existent upload_id parameter is already being validated and being used to get the related project and attach it to request object.
I see the reason to add this new function is to display project name in the error page.
If an upload_id parameter is passed to this action, the project object is already attached to request by "checkForCorrectUploadId" method. The reason you cannot see the project name is that the "Download Final Fix" link has no upload_id. Because there is no final fix uploaded, hence the "Download" link should not be visible.
This new method makes the getProject db query for the second time and query the user roles for the second time unnecessarily.
Furthermore, let's say I want to download a final fix that I don't have an access. What will happen if I use an upload_id that I want to download and use a project_id belongs to another project that I have full access? There is no additional check to verify if given uid belongs to given pid.
My recommendation is to remove the new functions and pid parameter from DownloadFinalFix action and simply hide "download final fix" link if there is no final fix (group.finalFix) in approval phase.

2022-12-19 10:22 UTC, dedywahyudi commented on src/main/java/com/cronos/onlinereview/actions/projectdetails/BaseProjectDetailsAction.java
> +    protected CorrectnessCheckResult checkForCorrectProjectId(HttpServletRequest request,
@eisbilir 

This is fixed now, please recheck

2022-12-19 10:27 UTC, eisbilir approved these changes

2022-12-20 04:33 UTC, merged